### PR TITLE
Update ch01.asciidoc - Airbitz to BlueWallet

### PR DESCRIPTION
**Pull request by krupawan5618**
-Changed Airbitz to Electrum
-Removed duplicate paragraph
-Removed dead links

### CODE REVIEW

**Review by wbnns — CHANGES_REQUESTED** [review]
@krupawan5618 

Thanks for working on this. For mobile stuff, let's default to BlueWallet here rather than Electrum, since BW is available for both iOS and Android -- more people will be able to compare what's being said to their own devices and follow along.

**Comment by wbnns** [comment]
@krupawan5618 

FYI, I just merged #893, so probably not too much left to do on this PR.

**Comment by krupawan5618** [comment]
Looks good now, consider merging

**Review by wbnns — APPROVED** [review]
@krupawan5618 

Thank you!

**Pull request merged**
