### PR TITLE
Discerning Bitcoin from bitcoin

### PR DESCRIPTION
**Pull request by tpmccallum**
It recently became clear to me that the holistic product/service/project “Bitcoin” is represented differently, in written communication online, in contrast to (actual rights to) a single “bitcoin” (or part there of). The difference is the capitalisation of b.

### CODE REVIEW

**Comment by tpmccallum** [comment]
I am happy to work through the whole book and capitalise Bitcoin where it refers to the product (and leave as lowercase where it refers to a coin), but only if you agree that this is needed. I don’t want to create unwanted pull requests. Please let me know either way.

**Comment by tpmccallum** [comment]
I am thinking that we could add something to clarify this in the book i.e.  “Throughout this book we’ll use the term “bitcoin” to refer to any quantity of bitcoin currency and “Bitcoin” to refer to the broader product/service”

**Comment by mihael** [comment]
Hi. Is there a product named Bitcoin? Isn't the currency Bitcoin? Cheers

**Comment by tpmccallum** [comment]
Hi @mihael 
Good question and happy to be wrong on this. It is hard to know because even in the Satoshi white paper the word Bitcoin only appears twice (once as the first letter of the title which is a capital and once in an email address). However, it is my understanding that the protocol is called Bitcoin and the units are bitcoin. Interestingly, this Bitcoin Wikipedia page < https://en.wikipedia.org/wiki/Bitcoin > ("terminology" section) reveals that there is no uniform convention for capitalization yet. Interesting hey?
Could just let it go I guess :)

**Comment by tpmccallum** [comment]
Hi @mihael 
Good question and happy to be wrong on this. It is hard to know because even in the Satoshi white paper the word Bitcoin only appears twice (once as the first letter of the title which is a capital and once in an email address). However, it is my understanding that the protocol is called Bitcoin and the units are bitcoin. Interestingly, this Bitcoin Wikipedia page < https://en.wikipedia.org/wiki/Bitcoin > ("terminology" section) reveals that there is no uniform convention for capitalization yet. Interesting hey?
Could just let it go I guess :)

**Comment by aantonop** [comment]
This is a very subjective issue, I know. But I decided not to make that distinction in the book, on purpose. It's too subtle, gets lost in speech and is not consistently applied in 99% of cases. So, I left it all lower case. People will have to distinguish the meaning from context. 

Thanks for offering to fix this, but I don't think it adds enough value to be worth such a massive edit.

**Comment by tpmccallum** [comment]
Thanks @aantonop , no sweat!

**Pull request closed without merging**
