### PR TITLE
Fixing book.asciidoc file includes to match actual file names.

### PR DESCRIPTION
**Pull request by jonathancross**
This fixes errors related to missing includes:
```
asciidoc: WARNING: book.asciidoc: line 5: include file not found: praise.asciidoc
asciidoc: WARNING: book.asciidoc: line 21: include file not found: ch06.asciidoc
asciidoc: WARNING: book.asciidoc: line 23: include file not found: ch07.asciidoc
asciidoc: WARNING: book.asciidoc: line 25: include file not found: ch08.asciidoc
asciidoc: WARNING: book.asciidoc: line 27: include file not found: ch09.asciidoc
asciidoc: WARNING: book.asciidoc: line 29: include file not found: ch10.asciidoc
asciidoc: WARNING: book.asciidoc: line 41: include file not found: index.asciidoc
asciidoc: WARNING: book.asciidoc: line 43: include file not found: colo.asciidoc
```

### CODE REVIEW

**Comment by jonathancross** [comment]
Hi @wbnns any concerns here?

**Comment by wbnns** [comment]
@jonathancross Hi there! Apologies, I haven't had a chance to review these yet.

**Comment by wbnns** [comment]
@jonathancross Thanks a bunch, this looks good. Merged. 👍

**Comment by jonathancross** [comment]
@wbnns Great!

**Comment by jonathancross** [comment]
Just saw the note about the [revert](https://github.com/bitcoinbook/bitcoinbook/commit/5e9f9e6e72dccebac91dfb5196b2c8ad42319a77):

> book.asciidoc is being used for the O'Reilly early-release program and should only contain the completed chapters from the in-progress second edition of the book. Please do not modify, thanks!

Got it. ;-)

**Pull request merged**
