### PR TITLE
ch04: Fix mathematical terms

### PR DESCRIPTION
**Pull request by hebasto**
1. EC multiplication is a "one-way" function, not a "trapdoor" one. There is no information that makes reverse function easy. See:
  - https://en.wikipedia.org/wiki/Trapdoor_function
  - https://en.wikipedia.org/wiki/One-way_function

2. The "discrete logarithm" is more usual term for the reverse operation for EC multiplication.

### CODE REVIEW

**Comment by glozow** [comment]
(1) ACK, there is no trapdoor in discrete log problems
(2) not a cryptographer, but I personally haven't heard division used in this context 🤷

**Comment by LarryRuane** [comment]
Changing "trap door" to "one way" is definitely a good change, but I think the author uses the term "division" as a direct contrast to "multiplication" earlier in the same sentence. So my suggestion is to replace "division" with "division, or finding the discrete logarithm" so the reader knows those are the same in the current context.

**Comment by aantonop** [comment]
> Changing "trap door" to "one way" is definitely a good change, but I think the author uses the term "division" as a direct contrast to "multiplication" earlier in the same sentence. So my suggestion is to replace "division" with "division, or finding the discrete logarithm" so the reader knows those are the same in the current context.

Yes, I like this formulation. Keep in mind, this is one of the more difficult parts of the book for non-experts to understand and I've tried to keep it as simple as possible.

@hebasto what do you think of "division (or finding the discrete logarithm)"

**Comment by hebasto** [comment]
@aantonop 
> Yes, I like this formulation. Keep in mind, this is one of the more difficult parts of the book for non-experts to understand and I've tried to keep it as simple as possible.

Right.

> @hebasto what do you think of "division (or finding the discrete logarithm)"

_... and impossible to do in the reverse direction (division (or finding the discrete logarithm))._  -- nested parentheses look a bit strange :)

Suggested:

_... and impossible to do in the reverse direction ("division", or finding the discrete logarithm)._

**Pull request merged**
