### PR TITLE
total blocks when the reward is less than 1satoshi

### PR DESCRIPTION
**Pull request by takaya-imai**
I calculated a reward per a block and total blocks over time like below.
Total blocks is around half of 13,230,000 when the reward is less than 1satoshi?

```
year: 2009 - 2012, reward:5000000000, halving count: 0, blocks: 0 - 209999, issued bitcoins: 0 - 1050000000000000
year: 2013 - 2016, reward:2500000000, halving count: 1, blocks: 210000 - 419999, issued bitcoins: 1050000000000000 - 1575000000000000
year: 2017 - 2020, reward:1250000000, halving count: 2, blocks: 420000 - 629999, issued bitcoins: 1575000000000000 - 1837500000000000
year: 2021 - 2024, reward:625000000, halving count: 3, blocks: 630000 - 839999, issued bitcoins: 1837500000000000 - 1968750000000000
year: 2025 - 2028, reward:312500000, halving count: 4, blocks: 840000 - 1049999, issued bitcoins: 1968750000000000 - 2034375000000000
year: 2029 - 2032, reward:156250000, halving count: 5, blocks: 1050000 - 1259999, issued bitcoins: 2034375000000000 - 2067187500000000
year: 2033 - 2036, reward:78125000, halving count: 6, blocks: 1260000 - 1469999, issued bitcoins: 2067187500000000 - 2083593750000000
year: 2037 - 2040, reward:39062500, halving count: 7, blocks: 1470000 - 1679999, issued bitcoins: 2083593750000000 - 2091796875000000
year: 2041 - 2044, reward:19531250, halving count: 8, blocks: 1680000 - 1889999, issued bitcoins: 2091796875000000 - 2095898437500000
year: 2045 - 2048, reward:9765625, halving count: 9, blocks: 1890000 - 2099999, issued bitcoins: 2095898437500000 - 2097949218750000
year: 2049 - 2052, reward:4882812, halving count: 10, blocks: 2100000 - 2309999, issued bitcoins: 2097949218750000 - 2098974609270000
year: 2053 - 2056, reward:2441406, halving count: 11, blocks: 2310000 - 2519999, issued bitcoins: 2098974609270000 - 2099487304530000
year: 2057 - 2060, reward:1220703, halving count: 12, blocks: 2520000 - 2729999, issued bitcoins: 2099487304530000 - 2099743652160000
year: 2061 - 2064, reward:610351, halving count: 13, blocks: 2730000 - 2939999, issued bitcoins: 2099743652160000 - 2099871825870000
year: 2065 - 2068, reward:305175, halving count: 14, blocks: 2940000 - 3149999, issued bitcoins: 2099871825870000 - 2099935912620000
year: 2069 - 2072, reward:152587, halving count: 15, blocks: 3150000 - 3359999, issued bitcoins: 2099935912620000 - 2099967955890000
year: 2073 - 2076, reward:76293, halving count: 16, blocks: 3360000 - 3569999, issued bitcoins: 2099967955890000 - 2099983977420000
year: 2077 - 2080, reward:38146, halving count: 17, blocks: 3570000 - 3779999, issued bitcoins: 2099983977420000 - 2099991988080000
year: 2081 - 2084, reward:19073, halving count: 18, blocks: 3780000 - 3989999, issued bitcoins: 2099991988080000 - 2099995993410000
year: 2085 - 2088, reward:9536, halving count: 19, blocks: 3990000 - 4199999, issued bitcoins: 2099995993410000 - 2099997995970000
year: 2089 - 2092, reward:4768, halving count: 20, blocks: 4200000 - 4409999, issued bitcoins: 2099997995970000 - 2099998997250000
year: 2093 - 2096, reward:2384, halving count: 21, blocks: 4410000 - 4619999, issued bitcoins: 2099998997250000 - 2099999497890000
year: 2097 - 2100, reward:1192, halving count: 22, blocks: 4620000 - 4829999, issued bitcoins: 2099999497890000 - 2099999748210000
year: 2101 - 2104, reward:596, halving count: 23, blocks: 4830000 - 5039999, issued bitcoins: 2099999748210000 - 2099999873370000
year: 2105 - 2108, reward:298, halving count: 24, blocks: 5040000 - 5249999, issued bitcoins: 2099999873370000 - 2099999935950000
year: 2109 - 2112, reward:149, halving count: 25, blocks: 5250000 - 5459999, issued bitcoins: 2099999935950000 - 2099999967240000
year: 2113 - 2116, reward:74, halving count: 26, blocks: 5460000 - 5669999, issued bitcoins: 2099999967240000 - 2099999982780000
year: 2117 - 2120, reward:37, halving count: 27, blocks: 5670000 - 5879999, issued bitcoins: 2099999982780000 - 2099999990550000
year: 2121 - 2124, reward:18, halving count: 28, blocks: 5880000 - 6089999, issued bitcoins: 2099999990550000 - 2099999994330000
year: 2125 - 2128, reward:9, halving count: 29, blocks: 6090000 - 6299999, issued bitcoins: 2099999994330000 - 2099999996220000
year: 2129 - 2132, reward:4, halving count: 30, blocks: 6300000 - 6509999, issued bitcoins: 2099999996220000 - 2099999997060000
year: 2133 - 2136, reward:2, halving count: 31, blocks: 6510000 - 6719999, issued bitcoins: 2099999997060000 - 2099999997480000
year: 2137 - 2140, reward:1, halving count: 32, blocks: 6720000 - 6929999, issued bitcoins: 2099999997480000 - 2099999997690000
```

### CODE REVIEW

**Comment by dabura667** [comment]
@aantonop Let me also add this man is single handedly (with some help from myself and a few others) translating your entire book into Japanese, for free and out of his own desire to learn while translating.

**Comment by aantonop** [comment]
@takaya-imai please send me email to info@bitcoinbook.info so that we can coordinate japanese translation!

**Comment by takaya-imai** [comment]
@aantonop thanks a lot! I sent a mail to the address.

**Comment by wbnns** [comment]
@takaya-imai Hello, I just wanted to let you know that this correct has been made in the `develop` branch and that you've also been added to the list of GitHub contributors in the Preface. Thanks again!

**Pull request closed without merging**
