### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by mhchia**

### CODE REVIEW

**Comment by wbnns** [comment]
Hi @mhchia, just wanted to send you a note and let you know that the typo you identified has been corrected in the branch `binns-pr-cleanup` and will be merged soon. Also, I've added you to the list of GitHub contributors in `preface.asciidoc`. We appreciate you taking the time to fix this!

**Comment by mhchia** [comment]
Thank you very much!
However, I didn't see my name.
Is it in the `preface.asciidoc` ?

**Comment by wbnns** [comment]
@mhchia You're welcome! Yes sir - [here's the link](https://github.com/bitcoinbook/bitcoinbook/blob/develop/preface.asciidoc) - it's in the `develop` branch, now. Thanks again for the contribution. 👍

**Comment by mhchia** [comment]
Get it and saw it.
Thank you for your kind reply:)

**Comment by wbnns** [comment]
@mhchia You're most welcome.

**Pull request closed without merging**
