### PR TITLE
Fix link to coloredcoins.org

### PR DESCRIPTION
**Pull request by ghost**
It seems coloredcoins.org doesn't support https properly

### CODE REVIEW

**Comment by cherouvim** [comment]
Yes, it seems so. The cert has expired since 2016 and the https site currently only displays a "hello".

**Comment by wbnns** [comment]
@francyi @cherouvim Thank you both, this is now fixed.

**Comment by ghost** [comment]
@wbnns I would be grateful if you could also add my full name in the list of contributors: Frank Höger

**Comment by wbnns** [comment]
@francyi No problem, done! I already had you in there, but just with your GitHub username (francyi).

**Pull request merged**
