### PR TITLE
fix Apostrophe unicode character problem

### PR DESCRIPTION
**Pull request by aminmazi**
the Apostrophe character in hardened key derivation doesn't render correctly in github

### CODE REVIEW

**Comment by aantonop** [comment]
It renders correctly on print and ebook. That overrides

**Comment by aminmazi** [comment]
The rendering problem is very confusing for Github readers. is there any way to fix this on Github too?

**Comment by aantonop** [comment]
File a bug report with GitHub to fix their Unicode rendering in the
asciidoc to HTML renderer?

**Comment by aminmazi** [comment]
> File a bug report with GitHub to fix their Unicode rendering in the asciidoc to HTML renderer?

Done!

**Pull request closed without merging**
