### PR TITLE
Additional BIP32 HD wallet resources

### PR DESCRIPTION
**Pull request by blmalone**

### CODE REVIEW

**Comment by blmalone** [comment]
Hey @aantonop, 

I've created a pull request as per your request.

I've also included the [original XML file ](https://github.com/bitcoinbook/bitcoinbook/blob/2303c252ecb0507dee7d42377d22618af83f9e4f/images/configurable_images/mbc2_0514.xml) for the flowchart in the PR. **I can edit** this to be more in line with the books other diagrams upon request. 

Keen to help get more resources into the book on HD wallets so please let me know.

Medium post on HD wallets: 
https://medium.com/@blainemalone01/hd-wallets-why-hardened-derivation-matters-89efcdc71671

You'll notice that I have more text relating to the flow chart within the article. I can try to embed this into chapter five if we deem it necessary. 


Thank you,
Blaine

**Comment by wbnns** [comment]
@blmalone 

Thanks for putting this together. Not sure if at the very end of the chapter is where this should go. Also, it might be helpful to have a bit more elaborative text (as opposed to just adding the figure), expanding a bit on how it ties in, etc.

**Comment by blmalone** [comment]
@wbnns Thanks for your reply, I'll work on adding in some context. Do you have a date in mind when I should have this completed? I'm just thinking that you may have a deadline with a publisher etc.

**Comment by wbnns** [comment]
@blmalone 

Hello, no, thank you for asking - but please feel free to open a new pull request or comment on this one if/when you have some updates, and we'll review it for potential inclusion in future editions.

**Comment by blmalone** [comment]
Cool, I'll have a look at this soon. Thanks

**Comment by wbnns** [comment]
Closing for now.

**Comment by blmalone** [comment]
@wbinns This got pushed down my list of things to do, when's the next book scheduled? I could get a first draft pretty soon.

**Comment by wbnns** [comment]
@blmalone 

No worries. :) Regarding a 3rd edition, will yield to @aantonop to give updates when they become available.

**Pull request closed without merging**
