### PR TITLE
Update ch03.asciidoc

### PR DESCRIPTION
**Pull request by erikwam**
Changed type-1 to type-0 for non-deterministic keys.

### CODE REVIEW

**Comment by enderminh** [comment]
Good catch! Merging.

**Comment by erikwam** [comment]
Thanks.
I hope you also noticed the comment I made on issue #18, May 12.

In short. The text should be changed in the following places:
- The text above figure 9 in chapter 2 ("...The blocks above count as
  “confirmations” ").
- The "tip box" in chapter 3 ("Absence of a transaction hash in the
  blockchain does not mean the transaction was not processed").

/Erik

**Comment by enderminh** [comment]
Hi Eric,

  I did, but it was just a new comment to an existing issue, which I've
already assigned to Andreas and remains open.

   Once he has the time to address them, he will have to change all those
three locations. We all agree that the current definition of # of
confirmations is incorrect, but Andreas will have to change this as it's
not just a minor spelling/grammatical fix.

Thanks for checking in though. Appreciated.

Cheers,
Minh T. Nguyen

**Comment by erikwam** [comment]
Sounds good - Just wanted to make sure you didn't miss it.

Best.
Erik Wahlström

**Pull request merged**
