### PR TITLE
Added bcoin under alt_libraries

### PR DESCRIPTION
**Pull request by ajile-in**
Kindly review and accept.

### CODE REVIEW

**Comment by wbnns** [comment]
@jadhavajay Thanks for submitting this. Could you please spell `javascript` as `JavaScript` for consistency, so that it matches how it is referenced in the section?

**Comment by wbnns** [comment]
I'm closing this for now to keep the repository up to date, but please feel free to reopen this against the errata branch if you'd like to make the spelling/consistency change.

**Comment by ajile-in** [comment]
Sure. I will make the change you suggested, and will submit PR again.

**Comment by wbnns** [comment]
@jadhavajay Thanks!

**Pull request closed without merging**
