### PR TITLE
ch01 client category updates + ch02 confirmation count wording updates

### PR DESCRIPTION
**Pull request by mruddy**
- updated the bitcoin client categories to include hybrid clients (such as bitgo.com, and also how the current blockchain.info wallet works: https://blockchain.info/wallet/how-it-works).
- other minor updates to incorporate the client category updates
- updated methods for a new user to obtain bitcoin

### CODE REVIEW

**Comment by enderminh** [comment]
Hi mruddy,

  Just wanted to let you know that I am seeing this pull request. I need to get some confirmation by Andreas first on some issues in this large pull request before I merge it in.

Thanks,
Minh T. Nguyen.

**Comment by mruddy** [comment]
Cool, I just merged in the latest changes from the upstream repo. I'm happy to help if you need something in these updates changed.

Also, minor note, in ch01, the section about Coinbase being an exchange etc..., I saw that Lornestar made a recent change (commit d3d95954e5907aee0ffe7186396ed0088278256e), but I left Coinbase labeled as an exchange because the Wikipedia entry [http://en.wikipedia.org/wiki/Coinbase] says in the first sentence, "Coinbase is a Bitcoin exchange headquartered ...".

**Comment by Lornestar** [comment]
All good mruddy.  I think trying everyone has different ways of explaining what coinbase is, cause it means different things to different people.

**Comment by mruddy** [comment]
stale, closing

**Pull request closed without merging**
