### PR TITLE
Fix spelling of Qt

### PR DESCRIPTION
**Pull request by diegoviola**
QT is considered a typo, Qt is the proper term.

### CODE REVIEW

**Comment by DavidGeeraerts** [comment]
Agree, just take a look at the project website for how it's referenced [Qt]:
http://www.qt.io/

**Comment by diegoviola** [comment]
Ping?

**Comment by DavidGeeraerts** [comment]
Acronyms are usually capitalized, as it denotes an acronym. Since PING (Packet Internet Groper) is an acronym, it should be capitalized. The author, when referencing the PING program/tool, uses all upper case: http://ftp.arl.mil/mike/ping.html

**Comment by diegoviola** [comment]
Qt is not an acronym.

**Comment by DavidGeeraerts** [comment]
@diegoviola My comment was in relation to "Ping?", not Qt.

**Comment by diegoviola** [comment]
Ping?

**Pull request closed without merging**
